doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: "%env(resolve:DB_CONNECTION)%"
        host: "%env(resolve:DB_HOST)%"
        port: "%env(resolve:DB_PORT)%"
        dbname: "%env(resolve:DB_DATABASE)%"
        user: "%env(resolve:DB_USERNAME)%"
        password: "%env(resolve:DB_PASSWORD)%"

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        dir: "%kernel.project_dir%/src/Entity"
        prefix: 'App\Entity'
        alias: App
    dql:
      numeric_functions:
        rand: DoctrineExtensions\Query\Mysql\Rand

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
